packages:
  - apps/*
  - packages/*
  - packages/*/integration-tests/__fixtures__/*
  - scripts

catalog:
  "@axe-core/react": ^4.10.2
  "@coral-xyz/anchor": ^0.31.1
  "@cprussin/eslint-config": ^5.0.0
  "@cprussin/jest-config": ^3.1.2
  "@cprussin/prettier-config": ^3.0.0
  "@cprussin/transform-package-json": ^2.0.0
  "@cprussin/tsconfig": ^4.0.1
  "@metaplex-foundation/mpl-token-metadata": ^3.4.0
  "@metaplex-foundation/umi": ^1.2.0
  "@metaplex-foundation/umi-bundle-defaults": ^1.2.0
  "@next/third-parties": ^15.3.4
  "@noble/hashes": ^1.8.0
  "@phosphor-icons/react": ^2.1.10
  "@radix-ui/react-slot": ^1.1.1
  "@react-hookz/web": ^25.1.1
  "@solana/compat": ^2.1.1
  "@solana/kit": ^2.1.1
  "@solana/spl-token": ^0.4.13
  "@solana/wallet-adapter-base": ^0.9.23
  "@solana/wallet-adapter-react": ^0.15.35
  "@solana/wallet-adapter-react-ui": ^0.9.35
  "@solana/wallet-adapter-wallets": ^0.19.10
  "@solana/web3.js": ^1.92.3
  "@solana/webcrypto-ed25519-polyfill": ^2.3.0
  "@svgr/webpack": ^8.1.0
  "@swc/cli": ^0.7.7
  "@swc/core": ^1.12.7
  "@testing-library/dom": ^10.4.0
  "@testing-library/jest-dom": ^6.6.3
  "@testing-library/react": ^16.3.0
  "@types/bn.js": ^4.11.6
  "@types/jest": ^29.5.14
  "@types/node": ^24.0.1
  "@types/react": ^19.1.8
  "@types/react-dom": ^19.1.6
  "@types/yargs": ^17.0.33
  autoprefixer: ^10.4.20
  bn.js: ^5.1.2
  bs58: ^6.0.0
  class-variance-authority: ^0.7.1
  clsx: ^2.1.1
  eslint: ^9.28.0
  idb: ^8.0.3
  jest: ^29.7.0
  lucide-react: ^0.473.0
  modern-normalize: ^3.0.1
  next: ^15.1.5
  pino: ^9.7.0
  pino-pretty: ^13.0.0
  postcss: ^8.5.1
  prettier: ^3.5.3
  puppeteer: ^24.10.1
  react-aria: 3.41.1
  react-aria-components: 1.10.1
  react-dom: ^19.0.0
  react: ^19.0.0
  sass: ^1.89.2
  stylelint: ^16.21.0
  stylelint-config-standard-scss: ^15.0.1
  swr: ^2.3.3
  tailwind-merge: ^2.6.0
  tailwindcss-animate: ^1.0.7
  tailwindcss: ^3.4.17
  turbo: ^2.5.4
  typescript: ^5.8.3
  yargs: ^18.0.0
  zod: ^3.25.62

engineStrict: true

managePackageManagerVersions: false

onlyBuiltDependencies:
  - "@parcel/watcher"
  - "@swc/core"
  - bigint-buffer
  - blake-hash
  - bufferutil
  - esbuild
  - protobufjs
  - puppeteer
  - sharp
  - tiny-secp256k1
  - usb
  - utf-8-validate

packageManagerStrict: true

packageManagerStrictVersion: true

strictDepBuilds: true

strictPeerDependencies: false
