packages:
  - apps/*
  - packages/*
  - packages/*/integration-tests/__fixtures__/*
  - scripts/ts

catalog:
  "@axe-core/react": ^4.10.2
  "@changesets/cli": ^2.29.4
  "@better-builds/ts-duality": ^0.1.2
  "@babel/preset-typescript": ^7.27.1
  "@coral-xyz/anchor": ^0.31.1
  "@cprussin/eslint-config": ^5.0.0
  "@cprussin/jest-config": ^3.1.2
  "@cprussin/prettier-config": ^3.0.0
  "@cprussin/transform-package-json": ^2.1.0
  "@cprussin/tsconfig": ^4.0.1
  "@ledgerhq/hw-transport": ^6.31.12
  "@ledgerhq/hw-transport-node-hid": ^6.29.13
  "@metaplex-foundation/mpl-token-metadata": ^3.4.0
  "@metaplex-foundation/umi": ^1.2.0
  "@metaplex-foundation/umi-bundle-defaults": ^1.2.0
  "@metaplex-foundation/umi-web3js-adapters": ^1.4.1
  "@neondatabase/serverless": ^1.0.2
  "@next/third-parties": ^16.0.7
  "@noble/hashes": ^1.8.0
  "@phosphor-icons/react": ^2.1.10
  "@radix-ui/react-slot": ^1.1.1
  "@react-hookz/web": 25.1.1
  "@solana-mobile/wallet-adapter-mobile": ^2.2.4
  "@solana-program/token": ^0.5.1
  "@solana/compat": ^4.0.0
  "@solana/kit": ^4.0.0
  "@solana/spl-token": ^0.4.13
  "@solana/wallet-adapter-backpack": 0.1.14
  "@solana/wallet-adapter-base": 0.9.27
  "@solana/wallet-adapter-ledger": ^0.9.29
  "@solana/wallet-adapter-wallets": ^0.19.10
  "@solana/wallet-standard-features": ^1.3.0
  "@solana/wallet-standard-wallet-adapter-react": ^1.1.4
  "@solana/web3.js": ^1.92.3
  "@solana/webcrypto-ed25519-polyfill": ^2.3.0
  "@storybook/addon-styling-webpack": ^3.0.0
  "@storybook/addon-themes": ^10.1.2
  "@storybook/nextjs": ^10.1.2
  "@storybook/react": ^10.1.2
  "@svgr/webpack": ^8.1.0
  "@swc/cli": ^0.7.7
  "@swc/core": ^1.12.7
  "@testing-library/dom": ^10.4.0
  "@testing-library/jest-dom": ^6.6.3
  "@testing-library/react": ^16.3.0
  "@types/bn.js": ^4.11.6
  "@types/jest": ^29.5.14
  "@types/node": ^24.0.1
  "@types/pg": ^8.15.6
  "@types/react": ^19.1.8
  "@types/react-dom": ^19.1.6
  "@types/yargs": ^17.0.33
  "@wormhole-foundation/sdk": ^3.10.0
  "@wormhole-foundation/sdk-base": ^3.11.0
  "@wormhole-foundation/sdk-route-ntt": ^4.0.1
  "@wormhole-foundation/sdk-solana-core": ^3.10.0
  "@wormhole-foundation/sdk-solana-ntt": ^4.0.1
  "@yudiel/react-qr-scanner": ^2.3.1
  autoprefixer: ^10.4.20
  babel-plugin-react-compiler: 19.1.0-rc.1
  bn.js: ^5.1.2
  bs58: ^6.0.0
  copy-and-watch: ^0.1.8
  copyfiles: ^2.4.1
  class-variance-authority: ^0.7.1
  clsx: ^2.1.1
  dnum: ^2.15.0
  css-loader: ^7.1.2
  eslint: ^9.28.0
  idb: ^8.0.3
  jest: ^29.7.0
  lucide-react: ^0.473.0
  modern-normalize: ^3.0.1
  motion: ^12.23.16
  next: ^16.0.10
  pino: ^9.7.0
  pino-pretty: ^13.0.0
  postcss: ^8.5.1
  postcss-loader: ^8.1.1
  prettier: ^3.5.3
  puppeteer: ^24.10.1
  qrcode.react: ^4.2.0
  react: ^19.1.4
  react-aria: ^3.41.1
  react-aria-components: ^1.10.1
  react-dom: ^19.1.4
  sass: ^1.89.2
  sass-loader: ^16.0.5
  storybook: ^10.1.2
  stylelint: ^16.21.0
  style-loader: ^4.0.0
  stylelint-config-standard-scss: ^15.0.1
  swr: ^2.3.3
  thread-stream: ^3.1.0
  turbo: ^2.5.4
  typescript: ^5.8.3
  yargs: ^18.0.0
  zod: 3.25.67

engineStrict: true

managePackageManagerVersions: false

onlyBuiltDependencies:
  - "@parcel/watcher"
  - "@swc/core"
  - bigint-buffer
  - blake-hash
  - bufferutil
  - core-js-pure
  - esbuild
  - node-hid
  - protobufjs
  - puppeteer
  - secp256k1
  - sharp
  - tiny-secp256k1
  - usb
  - utf-8-validate

packageManagerStrict: true

packageManagerStrictVersion: true

strictDepBuilds: true

strictPeerDependencies: false
