packages:
  - apps/*
  - packages/*

catalog:
  "@coral-xyz/anchor": ^0.31.1
  "@cprussin/eslint-config": ^4.0.2
  "@cprussin/jest-config": ^2.0.2
  "@cprussin/prettier-config": ^2.2.2
  "@cprussin/tsconfig": ^3.1.2
  "@radix-ui/react-slot": ^1.1.1
  "@solana/wallet-adapter-base": ^0.9.23
  "@solana/wallet-adapter-react": ^0.15.35
  "@solana/wallet-adapter-react-ui": ^0.9.35
  "@solana/wallet-adapter-wallets": 0.19.10
  "@solana/spl-token": 0.4.13
  "@solana/web3.js": 1.92.3
  "@types/react": 19.0.7
  autoprefixer: ^10.4.20
  bs58: ^6.0.0
  class-variance-authority: ^0.7.1
  clsx: ^2.1.1
  eslint: ^9.28.0
  jest: ^29.7.0
  lucide-react: ^0.473.0
  next: ^15.1.5
  pino-pretty: ^13.0.0
  postcss: ^8.5.1
  prettier: ^3.5.3
  react-dom: 19.0.0
  react: 19.0.0
  tailwind-merge: ^2.6.0
  tailwindcss-animate: ^1.0.7
  tailwindcss: ^3.4.17
  turbo: ^2.5.4
  typescript: ^5.8.3
  zod: ^3.25.62

engineStrict: true

managePackageManagerVersions: false

onlyBuiltDependencies:
  - sharp
  - bigint-buffer
  - bufferutil
  - utf-8-validate

packageManagerStrict: true

packageManagerStrictVersion: true

strictDepBuilds: true

strictPeerDependencies: false
