/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import type { Address, ProgramDerivedAddress } from "@solana/kit";
import {
  getProgramDerivedAddress,
  getU32Encoder,
  getUtf8Encoder,
} from "@solana/kit";

export type RegistrySeeds = {
  /** The seed value for the registry */
  seed: number;
};

export async function findRegistryPda(
  seeds: RegistrySeeds,
  config: { programAddress?: Address | undefined } = {},
): Promise<ProgramDerivedAddress> {
  const {
    programAddress = "NameHB3aMPDhcaPgrRXnP6NgrQ6MoBPMFz2FisW7rBs" as Address<"NameHB3aMPDhcaPgrRXnP6NgrQ6MoBPMFz2FisW7rBs">,
  } = config;
  return await getProgramDerivedAddress({
    programAddress,
    seeds: [
      getUtf8Encoder().encode("registry"),
      getU32Encoder().encode(seeds.seed),
    ],
  });
}
