/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import type { Address, ProgramDerivedAddress } from "@solana/kit";
import {
  getAddressEncoder,
  getProgramDerivedAddress,
  getUtf8Encoder,
} from "@solana/kit";

export type ReverseRecordSeeds = {
  /** The registry account address */
  registry: Address;
  /** The owner's public key */
  owner: Address;
};

export async function findReverseRecordPda(
  seeds: ReverseRecordSeeds,
  config: { programAddress?: Address | undefined } = {},
): Promise<ProgramDerivedAddress> {
  const {
    programAddress = "NameHB3aMPDhcaPgrRXnP6NgrQ6MoBPMFz2FisW7rBs" as Address<"NameHB3aMPDhcaPgrRXnP6NgrQ6MoBPMFz2FisW7rBs">,
  } = config;
  return await getProgramDerivedAddress({
    programAddress,
    seeds: [
      getUtf8Encoder().encode("reverse_record"),
      getAddressEncoder().encode(seeds.registry),
      getAddressEncoder().encode(seeds.owner),
    ],
  });
}
