/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import type {
  Account,
  Address,
  EncodedAccount,
  FetchAccountConfig,
  FetchAccountsConfig,
  FixedSizeCodec,
  FixedSizeDecoder,
  FixedSizeEncoder,
  MaybeAccount,
  MaybeEncodedAccount,
  ReadonlyUint8Array,
} from "@solana/kit";
import {
  assertAccountExists,
  assertAccountsExist,
  combineCodec,
  decodeAccount,
  fetchEncodedAccount,
  fetchEncodedAccounts,
  fixDecoderSize,
  fixEncoderSize,
  getAddressDecoder,
  getAddressEncoder,
  getArrayDecoder,
  getArrayEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getI64Decoder,
  getI64Encoder,
  getStructDecoder,
  getStructEncoder,
  getU8Decoder,
  getU8Encoder,
  transformEncoder,
} from "@solana/kit";

export const NAME_RECORD_DISCRIMINATOR: ReadonlyUint8Array = new Uint8Array([
  254, 22, 17, 161, 229, 49, 238, 105,
]);

export function getNameRecordDiscriminatorBytes(): ReadonlyUint8Array {
  return fixEncoderSize(getBytesEncoder(), 8).encode(NAME_RECORD_DISCRIMINATOR);
}

export type NameRecord = {
  discriminator: ReadonlyUint8Array;
  /** The registry that this name record belongs to. */
  registry: Address;
  /** The name of the record, UTF-8 encoded. */
  name: number[];
  /** Bump seed. */
  bump: number;
  /**
   * The address which this name resolves to.
   *
   * When owned by the registry (not yet claimed), this can be set by the operator
   * to reserve the name for a specific address. Only that address will be able to
   * claim the name. After claiming, the owner can update this to any address.
   */
  targetAddress: Address;
  /** The mint of the NFT which represents this name. */
  mint: Address;
  /** Unix timestamp of when this name was created. */
  createdAt: bigint;
  /** Unix timestamp of when this name expires. */
  expiresAt: bigint;
};

export type NameRecordArgs = {
  /** The registry that this name record belongs to. */
  registry: Address;
  /** The name of the record, UTF-8 encoded. */
  name: number[];
  /** Bump seed. */
  bump: number;
  /**
   * The address which this name resolves to.
   *
   * When owned by the registry (not yet claimed), this can be set by the operator
   * to reserve the name for a specific address. Only that address will be able to
   * claim the name. After claiming, the owner can update this to any address.
   */
  targetAddress: Address;
  /** The mint of the NFT which represents this name. */
  mint: Address;
  /** Unix timestamp of when this name was created. */
  createdAt: number | bigint;
  /** Unix timestamp of when this name expires. */
  expiresAt: number | bigint;
};

export function getNameRecordEncoder(): FixedSizeEncoder<NameRecordArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      ["registry", getAddressEncoder()],
      ["name", getArrayEncoder(getU8Encoder(), { size: 63 })],
      ["bump", getU8Encoder()],
      ["targetAddress", getAddressEncoder()],
      ["mint", getAddressEncoder()],
      ["createdAt", getI64Encoder()],
      ["expiresAt", getI64Encoder()],
    ]),
    (value) => ({ ...value, discriminator: NAME_RECORD_DISCRIMINATOR }),
  );
}

export function getNameRecordDecoder(): FixedSizeDecoder<NameRecord> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    ["registry", getAddressDecoder()],
    ["name", getArrayDecoder(getU8Decoder(), { size: 63 })],
    ["bump", getU8Decoder()],
    ["targetAddress", getAddressDecoder()],
    ["mint", getAddressDecoder()],
    ["createdAt", getI64Decoder()],
    ["expiresAt", getI64Decoder()],
  ]);
}

export function getNameRecordCodec(): FixedSizeCodec<
  NameRecordArgs,
  NameRecord
> {
  return combineCodec(getNameRecordEncoder(), getNameRecordDecoder());
}

export function decodeNameRecord<TAddress extends string = string>(
  encodedAccount: EncodedAccount<TAddress>,
): Account<NameRecord, TAddress>;
export function decodeNameRecord<TAddress extends string = string>(
  encodedAccount: MaybeEncodedAccount<TAddress>,
): MaybeAccount<NameRecord, TAddress>;
export function decodeNameRecord<TAddress extends string = string>(
  encodedAccount: EncodedAccount<TAddress> | MaybeEncodedAccount<TAddress>,
): Account<NameRecord, TAddress> | MaybeAccount<NameRecord, TAddress> {
  return decodeAccount(
    encodedAccount as MaybeEncodedAccount<TAddress>,
    getNameRecordDecoder(),
  );
}

export async function fetchNameRecord<TAddress extends string = string>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig,
): Promise<Account<NameRecord, TAddress>> {
  const maybeAccount = await fetchMaybeNameRecord(rpc, address, config);
  assertAccountExists(maybeAccount);
  return maybeAccount;
}

export async function fetchMaybeNameRecord<TAddress extends string = string>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig,
): Promise<MaybeAccount<NameRecord, TAddress>> {
  const maybeAccount = await fetchEncodedAccount(rpc, address, config);
  return decodeNameRecord(maybeAccount);
}

export async function fetchAllNameRecord(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Address[],
  config?: FetchAccountsConfig,
): Promise<Account<NameRecord>[]> {
  const maybeAccounts = await fetchAllMaybeNameRecord(rpc, addresses, config);
  assertAccountsExist(maybeAccounts);
  return maybeAccounts;
}

export async function fetchAllMaybeNameRecord(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Address[],
  config?: FetchAccountsConfig,
): Promise<MaybeAccount<NameRecord>[]> {
  const maybeAccounts = await fetchEncodedAccounts(rpc, addresses, config);
  return maybeAccounts.map((maybeAccount) => decodeNameRecord(maybeAccount));
}
