/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import type {
  Account,
  Address,
  EncodedAccount,
  FetchAccountConfig,
  FetchAccountsConfig,
  FixedSizeCodec,
  FixedSizeDecoder,
  FixedSizeEncoder,
  MaybeAccount,
  MaybeEncodedAccount,
  ReadonlyUint8Array,
} from "@solana/kit";
import {
  assertAccountExists,
  assertAccountsExist,
  combineCodec,
  decodeAccount,
  fetchEncodedAccount,
  fetchEncodedAccounts,
  fixDecoderSize,
  fixEncoderSize,
  getAddressDecoder,
  getAddressEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  transformEncoder,
} from "@solana/kit";

export const REVERSE_RECORD_DISCRIMINATOR: ReadonlyUint8Array = new Uint8Array([
  125, 98, 59, 20, 159, 18, 85, 123,
]);

export function getReverseRecordDiscriminatorBytes(): ReadonlyUint8Array {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    REVERSE_RECORD_DISCRIMINATOR,
  );
}

export type ReverseRecord = {
  discriminator: ReadonlyUint8Array;
  /** The registry this reverse record belongs to */
  registry: Address;
  /** The address this reverse record is for */
  owner: Address;
  /** The primary name record for this address */
  nameRecord: Address;
};

export type ReverseRecordArgs = {
  /** The registry this reverse record belongs to */
  registry: Address;
  /** The address this reverse record is for */
  owner: Address;
  /** The primary name record for this address */
  nameRecord: Address;
};

export function getReverseRecordEncoder(): FixedSizeEncoder<ReverseRecordArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      ["registry", getAddressEncoder()],
      ["owner", getAddressEncoder()],
      ["nameRecord", getAddressEncoder()],
    ]),
    (value) => ({ ...value, discriminator: REVERSE_RECORD_DISCRIMINATOR }),
  );
}

export function getReverseRecordDecoder(): FixedSizeDecoder<ReverseRecord> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    ["registry", getAddressDecoder()],
    ["owner", getAddressDecoder()],
    ["nameRecord", getAddressDecoder()],
  ]);
}

export function getReverseRecordCodec(): FixedSizeCodec<
  ReverseRecordArgs,
  ReverseRecord
> {
  return combineCodec(getReverseRecordEncoder(), getReverseRecordDecoder());
}

export function decodeReverseRecord<TAddress extends string = string>(
  encodedAccount: EncodedAccount<TAddress>,
): Account<ReverseRecord, TAddress>;
export function decodeReverseRecord<TAddress extends string = string>(
  encodedAccount: MaybeEncodedAccount<TAddress>,
): MaybeAccount<ReverseRecord, TAddress>;
export function decodeReverseRecord<TAddress extends string = string>(
  encodedAccount: EncodedAccount<TAddress> | MaybeEncodedAccount<TAddress>,
): Account<ReverseRecord, TAddress> | MaybeAccount<ReverseRecord, TAddress> {
  return decodeAccount(
    encodedAccount as MaybeEncodedAccount<TAddress>,
    getReverseRecordDecoder(),
  );
}

export async function fetchReverseRecord<TAddress extends string = string>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig,
): Promise<Account<ReverseRecord, TAddress>> {
  const maybeAccount = await fetchMaybeReverseRecord(rpc, address, config);
  assertAccountExists(maybeAccount);
  return maybeAccount;
}

export async function fetchMaybeReverseRecord<TAddress extends string = string>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig,
): Promise<MaybeAccount<ReverseRecord, TAddress>> {
  const maybeAccount = await fetchEncodedAccount(rpc, address, config);
  return decodeReverseRecord(maybeAccount);
}

export async function fetchAllReverseRecord(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Address[],
  config?: FetchAccountsConfig,
): Promise<Account<ReverseRecord>[]> {
  const maybeAccounts = await fetchAllMaybeReverseRecord(
    rpc,
    addresses,
    config,
  );
  assertAccountsExist(maybeAccounts);
  return maybeAccounts;
}

export async function fetchAllMaybeReverseRecord(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Address[],
  config?: FetchAccountsConfig,
): Promise<MaybeAccount<ReverseRecord>[]> {
  const maybeAccounts = await fetchEncodedAccounts(rpc, addresses, config);
  return maybeAccounts.map((maybeAccount) => decodeReverseRecord(maybeAccount));
}
