name: Release SVM programs

on:
  pull_request:
  push:
    branches:
      - main
    paths:
      - programs/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
      - name: Install libusb
        run: sudo apt-get update && sudo apt-get install -y libusb-1.0-0-dev libudev-dev
      - name: Install Solana Verify CLI
        run: |
          cargo install solana-verify --git https://github.com/Ellipsis-Labs/solana-verifiable-build --rev 610cdc3
      - name: Build
        run: solana-verify build --base-image solanafoundation/solana-verifiable-build:2.2.18
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          path: target/deploy/*.so
          compression-level: 0
          retention-days: 90
